# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: prometheus-gitlab-notifier
before:
  hooks:
    - go mod tidy

builds:
  - main: "./cmd/{{.ProjectName}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux

dockers:
  - image_templates:
      - "fusakla/{{.ProjectName}}:latest"
      - "fusakla/{{.ProjectName}}:{{ .Tag }}"
      - "fusakla/{{.ProjectName}}:v{{ .Major }}"
      - "fusakla/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"

archives:
  - replacements:
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
