---
version: 2.1


orbs:
  prometheus: prometheus/prometheus@0.1.0

executors:
  # Whenever the Go version is updated here, .travis.yml and .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.12

jobs:
  test:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run: make
    - prometheus/store_artifact:
        file: prometheus-gitlab-notifier

  publish_master:
    description: |
      Build and publish container images from the master branch.
    docker:
    - image: circleci/golang
    steps:
    - prometheus/setup_build_environment
    - prometheus/publish_images:
        login_variable: DOCKER_LOGIN
        organization: fusakla
        password_variable: DOCKER_PASSWORD
        registry: docker.io

  publish_release:
    description: Build and publish binaries and container images for a given release tag.
    docker:
    - image: circleci/golang
    steps:
    - prometheus/setup_build_environment
    - run: promu crossbuild tarballs
    - run: promu checksum .tarballs
    - run: promu release .tarballs
    - prometheus/store_artifacts:
        destination: releases
        path: .tarballs
    - prometheus/publish_release_images:
        login_variable: DOCKER_LOGIN
        organization: fusakla
        password_variable: DOCKER_PASSWORD
        registry: docker.io



workflows:
  version: 2
  prometheus-gitlab-notifier:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - publish_master:
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - publish_release:
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
