apiVersion: v1
kind: Service
metadata:
  name: prometheus-gitlab-notifier
  labels:
    app: prometheus-gitlab-notifier
spec:
  ports:
    - port: 9629
      protocol: TCP
  selector:
    app: prometheus-gitlab-notifier
